import React from 'react'

function layout({children}) {
  return (
    <div>
      {children}

      {/* // */}
      import { Geist, Geist_Mono } from "next/font/google";
      import "./globals.css";
      
      const geistSans = Geist
        variable: "--font-geist-sans",
        subsets: ["latin"],
      
      
      const geistMono = Geist_Mono({
        variable: "--font-geist-mono",
        subsets: ["latin"],
      });
      
      metadata = 
        title: "Create Next App",
        description: "Generated by create next app",
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              {children}
            </body>
          </html>

      
      
    </div>
  )
}

export default layout
